const contractAddress = "YOUR CONTRACT ADDRESS"; // Replace with your own contract address
const chain = 'rinkeby'; // goerli, polygon, or ethereum

const welcome_h1 = "Meet the Urbs";
const welcome_h2 = "Connect to MetaMask to Get Started";
const welcome_p = 'You think you know the scene, the destruction of historic buildings, replaced by cities. Those cities fabricate amenities and resources, pouring into urban areas that portray a facade and in reality, have very little or nothing at all. A concrete jungle is developed, with so-called slums being replaced by far worse ones. Primitive nature distorted. The ecosystem has completely and utterly failed. Carnage, in a reality where nothing is real. The city is not a concrete jungle… it’s a human zoo. Introducing a collection of 10999 URBS brought to you by Urban Labs. Representing a breath of fresh air amidst the concrete jungle of anonymous urban life and an opportunity to rise above. Each trait is hand drawn and aesthetically unique. Inspired by everything we love and fear. Mother natures war against humanity. Humanities systematic war against humanity. Even though the world is f*cked. We are doing it for the culture. Long live URBnation';
const h1_presale_coming_soon = "NFT Drop Coming Soon!!";
const h1_presale_mint = "Pre-Sale Minting Open!!";
const h1_public_mint = "Public Minting Open!!";
const h2_presale_coming_soon = "Pre-Sale Minting Countdown";
const h2_presale_mint = "Public Minting Countdown";
const p_presale_coming_soon = "We are working hard to launch the NFT Collection. Stay tuned for updates!";
const p_presale_mint_not_whitelisted = "You are not whitelisted for the pre-sale.. 😢";
const p_presale_mint_whitelisted = "You're on the whitelist for the pre-sale! 🎉";
const p_presale_mint_already_minted = "You've already claimed your whitelist mint. Thank you! 🎉";
const p_public_mint = "No whitelist needed. Public minting is now open! 🎉";
const button_presale_coming_soon = "Get on the Whitelist";
const button_presale_mint_whitelisted = "Mint Your Special NFT";
const button_presale_mint_not_whitelisted = "Get on the Whitelist";
const button_presale_already_minted = "Join The Community";
const button_public_mint = "Mint Your NFT";
const mint_failed = "Minting failed. 😢 Please try again.";
